site_name: Mkdocs Project with User Authentications
site_url: ''
use_directory_urls: False
# repo_url: https://github.com/ionescuig/django-mkdocs.git

markdown_extensions:
  - admonition

theme:
  name: material

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gabriel-ionescu

nav:
  - Welcome: index.md
  - How To:
    - Use markdown: how-to/use-markdown.md
    - Add new documentation page: how-to/add-new-documentation-page.md
    - Create link to a page in the documentation: how-to/create-link-to-a-page-in-the-documentation.md
