site_name: Mkdocs Project with User Authentications
docs_dir: 'mkdocs'
site_dir: 'static/mkdocs_build'
site_url: ''
use_directory_urls: False
# repo_url: https://github.com/ionescuig/django-mkdocs.git

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gabriel-ionescu
    - icon: material/email
      link: mailto:ionescuig@yahoo.com

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material

plugins:
  - search

nav:
  - Welcome: index.md
  - How To:
    - Use markdown: how-to/use-markdown.md
    - Add new documentation page: how-to/add-new-documentation-page.md
    - Create link to a page in the documentation: how-to/create-link-to-a-page-in-the-documentation.md
  - Logout: accounts/logout/
  